sudo: false

language: java
jdk:
- oraclejdk8

before_install:
- openssl aes-256-cbc -K $encrypted_69ef0e89aa3f_key -iv $encrypted_69ef0e89aa3f_iv
  -in credentials.tar.gz.enc -out credentials.tar.gz -d
- tar -xzf credentials.tar.gz

script:
- ./gradlew appengineRun

#deploy:
#  provider: gae
#  keyfile: client-secret.json
#  project: kramolis-cr
#  no_promote: true
#  no_stop_previous_version: true
